import type { CatalogEntry, PublishedCatalog } from '../../src/types/catalog';
import { createEntryIndex, normalizeEntryLabel } from './entryIndex';
import { parseRelationship } from './parseRelationship';
import type { SourceRecord } from './sourceRecord';

type RelationshipField = 'challengeIds' | 'actionIds' | 'herbIds';

interface MutableEntry extends CatalogEntry {
  challengeIds: string[];
  actionIds: string[];
  herbIds: string[];
}

interface ResolveOptions {
  mode?: 'strict' | 'lenient' | 'auto-stub';
  inputDir?: string;
}

function addUnique(target: string[], value: string) {
  if (!target.includes(value)) {
    target.push(value);
  }
}

function createStubRecord(title: string, type: 'action' | 'challenge'): SourceRecord {
  // Generate ID from title by lowercasing and replacing spaces
  const id = title.toLowerCase().replace(/[\s\/\(\)]/g, '-');
  
  return {
    id,
    type,
    name: title,
    aliases: [],
    summary: '**Status:** Under construction — add real content later.',
    source: undefined,
    actions: [],
    healthChallenges: [],
    apothecaryApplications: undefined,
    sourcePath: `[auto-generated: ${title}]`,
  };
}

export function resolveRelationships(
  records: SourceRecord[],
  options: ResolveOptions = {},
): PublishedCatalog {
  const { mode = 'auto-stub' } = options;
  let index = createEntryIndex(records);
  let errors = [...index.errors];
  const entries = new Map<string, MutableEntry>();
  const autoGenerated = new Set<string>();

  for (const record of records) {
    entries.set(record.id, {
      id: record.id,
      type: record.type,
      name: record.name,
      ...(record.aliases.length > 0 ? { aliases: record.aliases } : {}),
      ...(record.summary ? { summary: record.summary } : {}),
      ...(record.source ? { source: record.source } : {}),
      challengeIds: [],
      actionIds: [],
      herbIds: [],
      ...(record.apothecaryApplications
        ? { apothecaryApplications: record.apothecaryApplications }
        : {}),
    });
  }

  const resolve = (
    record: SourceRecord,
    value: string,
    field: string,
    expectedType: SourceRecord['type'],
  ): SourceRecord | undefined => {
    let target: string;
    try {
      target = parseRelationship(value, record.sourcePath, field).target;
    } catch (error) {
      errors.push(error instanceof Error ? error.message : String(error));
      return undefined;
    }

    const matches = index.byLabel.get(normalizeEntryLabel(target)) ?? [];
    
    if (matches.length === 0) {
      if (mode === 'auto-stub' && (expectedType === 'action' || expectedType === 'challenge')) {
        // Auto-generate stub entry
        const stubRecord = createStubRecord(target, expectedType);
        if (!autoGenerated.has(stubRecord.id)) {
          records.push(stubRecord);
          autoGenerated.add(stubRecord.id);
          entries.set(stubRecord.id, {
            id: stubRecord.id,
            type: stubRecord.type,
            name: stubRecord.name,
            summary: stubRecord.summary,
            challengeIds: [],
            actionIds: [],
            herbIds: [],
          });
          // Re-index to include the new stub
          index = createEntryIndex(records);
          return stubRecord;
        }
        return records.find(r => r.id === stubRecord.id);
      }
      
      if (mode === 'strict') {
        errors.push(
          `${record.sourcePath}: ${field} link "${value}" does not resolve to an approved entry`,
        );
      }
      // lenient mode: silently skip
      return undefined;
    }
    
    if (matches.length > 1) {
      const ambiguityError = `${record.sourcePath}: ${field} link "${value}" is ambiguous across ${matches.map(({ sourcePath }) => sourcePath).join(', ')}`;
      if (mode === 'strict') {
        errors.push(ambiguityError);
      }
      // lenient/auto-stub: silently skip
      return undefined;
    }

    const match = matches[0];
    if (match.type !== expectedType) {
      const typeError = `${record.sourcePath}: ${field} link "${value}" resolves to ${match.type}; expected ${expectedType}`;
      if (mode === 'strict') {
        errors.push(typeError);
      }
      // lenient/auto-stub: silently skip
      return undefined;
    }
    return match;
  };

  const link = (
    source: SourceRecord,
    value: string,
    field: string,
    expectedType: SourceRecord['type'],
    sourceField: RelationshipField,
    inverseField: RelationshipField,
  ) => {
    const target = resolve(source, value, field, expectedType);
    if (!target) return;
    const sourceEntry = entries.get(source.id);
    const targetEntry = entries.get(target.id);
    if (!sourceEntry || !targetEntry) {
      errors.push(`${source.sourcePath}: failed to index relationship "${value}"`);
      return;
    }
    addUnique(sourceEntry[sourceField], target.id);
    addUnique(targetEntry[inverseField], source.id);
  };

  for (const record of records) {
    record.actions.forEach((value, indexInField) => {
      link(
        record,
        value,
        `actions[${indexInField}]`,
        'action',
        'actionIds',
        record.type === 'herb' ? 'herbIds' : 'challengeIds',
      );
    });
    record.healthChallenges.forEach((value, indexInField) => {
      if (record.type !== 'herb') {
        errors.push(
          `${record.sourcePath}: health_challenges is allowed only on herb records`,
        );
        return;
      }
      link(
        record,
        value,
        `health_challenges[${indexInField}]`,
        'challenge',
        'challengeIds',
        'herbIds',
      );
    });
  }

  // Only throw errors in strict mode; lenient and auto-stub modes continue
  if (mode === 'strict' && errors.length > 0) {
    throw new Error(errors.join('\n'));
  }
  
  if (errors.length > 0) {
    console.warn(`\nWarnings (mode: ${mode}):\n${errors.join('\n')}\n`);
  }

  const sortedEntries = [...entries.values()]
    .map((entry) => {
      entry.challengeIds.sort();
      entry.actionIds.sort();
      entry.herbIds.sort();
      return entry;
    })
    .sort((left, right) => left.id.localeCompare(right.id, 'en'));

  if (autoGenerated.size > 0) {
    console.info(`\nAuto-generated ${autoGenerated.size} stub entries:`);
    [...autoGenerated].sort().forEach(id => console.info(`  - ${id}`));
  }

  return { schemaVersion: 1, entries: sortedEntries };
}
